name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Job
    steps:
      - name: Generate readme document
        uses: tkottke90/markdown-to-docx
        with:
          output-name: 'MyReadme.docx'
